name: "build docker images"

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REPOSITORY_ACCESS_TOKEN: ${{ secrets.DOCKER_REPOSITORY_ACCESS_TOKEN }}
  DOCKER_REPOSITORY_NAME: ${{ vars.DOCKER_REPOSITORY_NAME }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  # IMAGE_TAG: latest # $GITHUB_SHA::6


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}

    - name: install-kuma-ci-tools
      run: |
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
        go install github.com/kumahq/ci-tools/cmd/release-tool@latest

    - name: Install kumactl
      run: |
        curl -L https://docs.konghq.com/mesh/installer.sh | sh -
        cp kong-mesh-*/bin/kumactl /usr/local/bin/kumactl      

    - name: Docker login
      run: docker login  -u $DOCKER_REPOSITORY_NAME -p $DOCKER_REPOSITORY_ACCESS_TOKEN

    - name: Build 
      run: make images

    - name: Push Images
      env:
        ALLOW_PUSH: true
      run: make docker/push

    - name: Deploy Images
      run: kumactl install control-plane --registry=docker.io/mvatandoost | kubectl apply -f - 
      
   

