name: "build docker images"

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REPOSITORY_ACCESS_TOKEN: ${{ secrets.DOCKER_REPOSITORY_ACCESS_TOKEN }}
  DOCKER_REPOSITORY_NAME: ${{ vars.DOCKER_REPOSITORY_NAME }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ vars.CLUSTER_ZONE }}
  # IMAGE_TAG: latest # $GITHUB_SHA::6


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.CLUSTER_ZONE }}

    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    # - name: Save DigitalOcean kubeconfig with short-lived credentials
    #   run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}

    - name: install-kuma-ci-tools
      run: |
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
        go install github.com/kumahq/ci-tools/cmd/release-tool@latest

    - name: Install kumactl
      run: |
        curl -L https://docs.konghq.com/mesh/installer.sh | sh -
        cp kong-mesh-*/bin/kumactl /usr/local/bin/kumactl      

    - name: Docker login
      run: docker login  -u $DOCKER_REPOSITORY_NAME -p $DOCKER_REPOSITORY_ACCESS_TOKEN

    - name: download modules 
      run: go mod download

    - name: Build 
      run: make biuld

    - name: Build images 
      run: make images

    - name: Push Images
      env:
        ALLOW_PUSH: true
      run: make docker/push

    # - name: Deploy Images
    #   run: kumactl install control-plane --registry=docker.io/mvatandoost --log-level=debug --version=0.0.0-preview.vcc8450579-amd64 | kubectl apply -f - 
      
   

